name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build:
    needs: setup
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-latest, windows-latest]
        include:
          - os: macos-13
            archive: macos-13-x86_64.zip
          - os: macos-14
            archive: macos-14-arm64.zip
          - os: ubuntu-latest
            archive: ubuntu-latest.zip
          - os: windows-latest
            archive: windows-latest.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release

      - name: compress
        run: 7z a -tzip ${{matrix.archive}} ./target/wheels/*

      - name: upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{matrix.archive}}
